// Named strategy presets — EVOLVED roster. Generated by install-roster
// from a roster-evolve run on the bug-fixed sim. Names are preserved
// from the prior roster; attributes come from diversity-aware evolution
// against a co-evolving opponent pool. See pareto/src/roster-evolve.ts.

import type { BrainConfig } from "./types.js";

export const STRATEGY_NAMES = [
  "standby",
  "blitz",
  "incumbent",
  "pivot",
  "unicorn",
  "disruptor",
  "operator",
  "oracle",
  "shipper",
  "moonshot",
  "regulatory",
  "founder",
  "acolyte",
  "intern",
  "troll",
  "acquirer",
] as const;
export type StrategyName = (typeof STRATEGY_NAMES)[number];

export const STRATEGIES: Record<StrategyName, BrainConfig> = {
  // evolved id=standby spent=360 counters=1 internalWr=54.6% vsOldMeta=63.9%
  standby: {
    id: "standby",
    attributes: {
      burnRate: 0.435, moat: 70.6998, shipRate: 0.533, foresight: 0,
      pivotSpeed: 0.0083, leverage: 0.097, networking: 0.2887, hallucination: 0,
      spite: 0.1073, greed: 0.0295, pacing: 0.3545, cunning: 0.6129,
    },
  },
  // evolved id=blitz spent=360 counters=4 internalWr=46.6% vsOldMeta=49.0%
  blitz: {
    id: "blitz",
    attributes: {
      burnRate: 0.152, moat: 125.8167, shipRate: 0.3336, foresight: 0.0759,
      pivotSpeed: 0.2136, leverage: -0.1083, networking: 0.2777, hallucination: 0,
      spite: 0.3635, greed: 0.4325, pacing: 0.1303, cunning: 0.2097,
    },
  },
  // evolved id=incumbent spent=351 counters=3 internalWr=53.6% vsOldMeta=43.1%
  incumbent: {
    id: "incumbent",
    attributes: {
      burnRate: 0.3127, moat: 100.419, shipRate: 0.5746, foresight: 0,
      pivotSpeed: 0.2466, leverage: -1, networking: 0.6191, hallucination: 0,
      spite: 0.4493, greed: 0.2264, pacing: 0.0361, cunning: 0.4357,
    },
  },
  // evolved id=pivot spent=360 counters=4 internalWr=51.2% vsOldMeta=47.9%
  pivot: {
    id: "pivot",
    attributes: {
      burnRate: 0.18, moat: 102, shipRate: 0.35, foresight: 0.045,
      pivotSpeed: 0.26, leverage: -0.46, networking: 0.51, hallucination: 0,
      spite: 0.08, greed: 0.23, pacing: 0.38, cunning: 0.36,
    },
  },
  // evolved id=unicorn spent=337 counters=3 internalWr=58.2% vsOldMeta=45.8%
  unicorn: {
    id: "unicorn",
    attributes: {
      burnRate: 0.1525, moat: 34.2378, shipRate: 0.4839, foresight: 0.0788,
      pivotSpeed: 0, leverage: 0.2059, networking: 0.3605, hallucination: 0,
      spite: 0.0674, greed: 0.3723, pacing: 0.4318, cunning: 0,
    },
  },
  // evolved id=disruptor spent=360 counters=4 internalWr=51.2% vsOldMeta=46.2%
  disruptor: {
    id: "disruptor",
    attributes: {
      burnRate: 0.344, moat: 62.2425, shipRate: 0.3726, foresight: 0,
      pivotSpeed: 0.1242, leverage: -0.2844, networking: 0.4109, hallucination: 0,
      spite: 0.157, greed: 0.4777, pacing: 0.2777, cunning: 0.4491,
    },
  },
  // evolved id=operator spent=360 counters=3 internalWr=51.7% vsOldMeta=52.1%
  operator: {
    id: "operator",
    attributes: {
      burnRate: 0.4036, moat: 51.5687, shipRate: 0.4792, foresight: 0.0707,
      pivotSpeed: 0.0782, leverage: 0.0141, networking: 0.3785, hallucination: 0,
      spite: 0.0094, greed: 0.3856, pacing: 0.4083, cunning: 0,
    },
  },
  // evolved id=oracle spent=347 counters=7 internalWr=48.3% vsOldMeta=43.4%
  oracle: {
    id: "oracle",
    attributes: {
      burnRate: 0.2675, moat: 75, shipRate: 0.3368, foresight: 0.06,
      pivotSpeed: 0.3269, leverage: -0.12, networking: 0.2675, hallucination: 0,
      spite: 0.1753, greed: 0.19, pacing: 0.41, cunning: 0.15,
    },
  },
  // evolved id=shipper spent=360 counters=4 internalWr=50.9% vsOldMeta=43.1%
  shipper: {
    id: "shipper",
    attributes: {
      burnRate: 0.1528, moat: 54.6665, shipRate: 0.6498, foresight: 0.0644,
      pivotSpeed: 0.0828, leverage: -0.18, networking: 0.4012, hallucination: 0,
      spite: 0.07, greed: 0.4088, pacing: 0.5198, cunning: 0,
    },
  },
  // evolved id=moonshot spent=273 counters=2 internalWr=51.7% vsOldMeta=39.9%
  moonshot: {
    id: "moonshot",
    attributes: {
      burnRate: 0.1552, moat: 97.2608, shipRate: 0.4739, foresight: 0.0775,
      pivotSpeed: 0.0003, leverage: -0.1551, networking: 0.1396, hallucination: 0,
      spite: 0.4075, greed: 0.0469, pacing: 0.1331, cunning: 0.0234,
    },
  },
  // evolved id=regulatory spent=360 counters=6 internalWr=47.3% vsOldMeta=52.1%
  regulatory: {
    id: "regulatory",
    attributes: {
      burnRate: 0.1472, moat: 111.9975, shipRate: 0.3472, foresight: 0.0128,
      pivotSpeed: 0.276, leverage: -0.2062, networking: 0.3924, hallucination: 0,
      spite: 0.2138, greed: 0.385, pacing: 0.116, cunning: 0.5078,
    },
  },
  // evolved id=founder spent=350 counters=10 internalWr=38.3% vsOldMeta=46.9%
  founder: {
    id: "founder",
    attributes: {
      burnRate: 0.36, moat: 57, shipRate: 0.42, foresight: 0.0775,
      pivotSpeed: 0.13, leverage: -0.2511, networking: 0.43, hallucination: 0,
      spite: 0.04, greed: 0.51, pacing: 0.2319, cunning: 0.0234,
    },
  },
  // evolved id=acolyte spent=273 counters=4 internalWr=49.9% vsOldMeta=46.5%
  acolyte: {
    id: "acolyte",
    attributes: {
      burnRate: 0.1552, moat: 57, shipRate: 0.4161, foresight: 0.0775,
      pivotSpeed: 0.13, leverage: -0.0894, networking: 0.2835, hallucination: 0,
      spite: 0.1157, greed: 0.0736, pacing: 0.1331, cunning: 0.0234,
    },
  },
  // evolved id=intern spent=287 counters=3 internalWr=52.0% vsOldMeta=42.4%
  intern: {
    id: "intern",
    attributes: {
      burnRate: 0.1772, moat: 100.419, shipRate: 0.5823, foresight: 0,
      pivotSpeed: 0.1236, leverage: -1, networking: 0.5021, hallucination: 0,
      spite: 0.0633, greed: 0.2264, pacing: 0.039, cunning: 0.3544,
    },
  },
  // evolved id=troll spent=348 counters=8 internalWr=44.8% vsOldMeta=45.1%
  troll: {
    id: "troll",
    attributes: {
      burnRate: 0.1309, moat: 86.0481, shipRate: 0.4285, foresight: 0.0792,
      pivotSpeed: 0.0388, leverage: 0.0352, networking: 0.3864, hallucination: 0,
      spite: 0.3866, greed: 0.2611, pacing: 0.4168, cunning: 0,
    },
  },
  // evolved id=acquirer spent=355 counters=2 internalWr=49.8% vsOldMeta=56.6%
  acquirer: {
    id: "acquirer",
    attributes: {
      burnRate: 0.1472, moat: 111.9975, shipRate: 0.3472, foresight: 0.0128,
      pivotSpeed: 0.276, leverage: -0.1551, networking: 0.3924, hallucination: 0,
      spite: 0.6964, greed: 0.0469, pacing: 0.1325, cunning: 0.5078,
    },
  },
};

// A few illustrative DSL-based trajectories users can copy & tweak.
export const SAMPLE_TRAJECTORIES: BrainConfig[] = [
  {
    id: "ramp-aggro",
    attributes: {
      burnRate: "0.3 + 0.6 * clamp(tick / 1200, 0, 1)",
      moat: 90, shipRate: 0.9,
      pivotSpeed: "self.hp < 40 ? 0.9 : 0.2",
    },
  },
  {
    id: "oscillate-spacer",
    attributes: {
      burnRate: 0.6,
      moat: "90 + 30 * sin(tick * 0.013)",
      shipRate: 0.9, pivotSpeed: 0.6,
    },
  },
  {
    id: "panic-switcher",
    attributes: {
      burnRate: "self.hp < 30 ? 1.0 : 0.4",
      moat: "self.hp < 30 ? 0 : 100",
      shipRate: 1.0,
      hallucination: "self.hp < 20 ? 60 : 5",
    },
  },
];
