export declare const W = 1280;
export declare const H = 720;
export declare const ARENA_L = 56;
export declare const ARENA_R = 1224;
export declare const ARENA_T = 48;
export declare const FLOOR_Y = 640;
export declare const STEP: number;
export declare const GRAVITY = 2600;
export declare const WALL_SLIDE = 160;
export declare const COYOTE_TIME = 0.08;
export declare const JUMP_BUFFER_TIME = 0.09;
export declare const HIT_FREEZE = 0.055;
export declare const CLASH_FREEZE = 0.03;
export declare const STATS: {
    readonly speed: 380;
    readonly accel: 5600;
    readonly airAccel: 2300;
    readonly friction: 5400;
    readonly airDrag: 720;
    readonly jump: 1200;
    readonly jumpCut: 0.44;
    readonly wallJumpX: 480;
    readonly wallJumpY: 1100;
    readonly climbSpeed: 170;
    readonly sword: 52;
    readonly bodyW: 26;
    readonly bodyH: 52;
    readonly swipeTime: 0.12;
    readonly diveSpeed: 900;
    readonly diveDrift: 0.78;
    readonly hitPush: 380;
    readonly resistance: 1;
};
export declare const POINTS_TO_WIN_ROUND = 2;
export declare const ROUNDS_TO_WIN_MATCH = 2;
export declare const TIMEOUT_TIEBREAK = "round-score-kills-v1";
export declare const GOAL_TIMER_START = 10;
export declare const ROUND_TIMER_MAX_TICKS: number;
export declare const GOAL_DWELL_S = 0.12;
export declare const GOAL_DWELL_RADIUS = 40;
export declare const KILL_RESPAWN_S = 0.5;
export declare const DOUBLE_KO_RESPAWN_S = 0.6;
export declare const RESPAWN_INVULN_S = 0.08;
