// Named strategy presets — EVOLVED roster. Generated by install-roster
// from a roster-evolve run on the bug-fixed sim. Names are preserved
// from the prior roster; attributes come from diversity-aware evolution
// against a co-evolving opponent pool. See pareto/src/roster-evolve.ts.
export const STRATEGY_NAMES = [
    "standby",
    "blitz",
    "incumbent",
    "pivot",
    "unicorn",
    "disruptor",
    "operator",
    "oracle",
    "shipper",
    "moonshot",
    "regulatory",
    "founder",
    "acolyte",
    "intern",
    "troll",
    "acquirer",
];
export const STRATEGIES = {
    // evolved id=r0 spent=313 counters=6 internalWr=54.1% vsOldMeta=76.7%
    standby: {
        id: "standby",
        attributes: {
            burnRate: 0.66, moat: 159, shipRate: 0, foresight: 0,
            pivotSpeed: 0.08, leverage: -0.36, networking: 0.61, hallucination: 0,
            spite: -1, greed: 0.57, pacing: 0, cunning: 0.36,
        },
    },
    // evolved id=r1 spent=348 counters=2 internalWr=59.1% vsOldMeta=58.3%
    blitz: {
        id: "blitz",
        attributes: {
            burnRate: 0.01, moat: 0, shipRate: 0.03, foresight: 0.185,
            pivotSpeed: 0.93, leverage: -0.36, networking: 0, hallucination: 0,
            spite: 0.66, greed: 0.62, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r2 spent=360 counters=6 internalWr=49.1% vsOldMeta=56.3%
    incumbent: {
        id: "incumbent",
        attributes: {
            burnRate: 0, moat: 258, shipRate: 0.42, foresight: 0,
            pivotSpeed: 0, leverage: -1, networking: 0, hallucination: 0,
            spite: 0.06, greed: 0.93, pacing: 0.86, cunning: 0,
        },
    },
    // evolved id=r3 spent=360 counters=11 internalWr=34.1% vsOldMeta=58.7%
    pivot: {
        id: "pivot",
        attributes: {
            burnRate: 0, moat: 234, shipRate: 0.97, foresight: 0.17,
            pivotSpeed: 0.75, leverage: -1, networking: 0, hallucination: 0,
            spite: -1, greed: 0.42, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r4 spent=295 counters=12 internalWr=29.6% vsOldMeta=61.8%
    unicorn: {
        id: "unicorn",
        attributes: {
            burnRate: 0, moat: 243, shipRate: 0, foresight: 0.0275,
            pivotSpeed: 0.99, leverage: -1, networking: 0, hallucination: 0,
            spite: -1, greed: 1, pacing: 0, cunning: 0.04,
        },
    },
    // evolved id=r5 spent=277 counters=7 internalWr=53.9% vsOldMeta=63.5%
    disruptor: {
        id: "disruptor",
        attributes: {
            burnRate: 0, moat: 159, shipRate: 0, foresight: 0.0025,
            pivotSpeed: 0, leverage: -0.36, networking: 0, hallucination: 0,
            spite: 0.96, greed: 0.57, pacing: 0, cunning: 0.36,
        },
    },
    // evolved id=r6 spent=194 counters=3 internalWr=60.4% vsOldMeta=59.0%
    operator: {
        id: "operator",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 1, foresight: 0.0125,
            pivotSpeed: 0, leverage: -0.36, networking: 0, hallucination: 0,
            spite: -1, greed: 0.57, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r7 spent=359 counters=7 internalWr=39.4% vsOldMeta=61.5%
    oracle: {
        id: "oracle",
        attributes: {
            burnRate: 0.97, moat: 288, shipRate: 0.53, foresight: 0.1725,
            pivotSpeed: 0, leverage: -1, networking: 0, hallucination: 0,
            spite: -1, greed: 0.44, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r8 spent=359 counters=4 internalWr=65.2% vsOldMeta=43.8%
    shipper: {
        id: "shipper",
        attributes: {
            burnRate: 0.77, moat: 0, shipRate: 0, foresight: 0.1825,
            pivotSpeed: 0, leverage: -0.36, networking: 0.5, hallucination: 0,
            spite: 0.32, greed: 0.61, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r9 spent=353 counters=4 internalWr=54.7% vsOldMeta=60.4%
    moonshot: {
        id: "moonshot",
        attributes: {
            burnRate: 1, moat: 195, shipRate: 0, foresight: 0,
            pivotSpeed: 0, leverage: -1, networking: 0, hallucination: 0,
            spite: 0.02, greed: 0.4, pacing: 0, cunning: 0.97,
        },
    },
    // evolved id=r10 spent=345 counters=4 internalWr=54.8% vsOldMeta=71.2%
    regulatory: {
        id: "regulatory",
        attributes: {
            burnRate: 0.59, moat: 159, shipRate: 0, foresight: 0,
            pivotSpeed: 0.08, leverage: -0.36, networking: 0, hallucination: 0,
            spite: -0.9, greed: 0.57, pacing: 1, cunning: 0.31,
        },
    },
    // evolved id=r11 spent=360 counters=10 internalWr=31.2% vsOldMeta=55.9%
    founder: {
        id: "founder",
        attributes: {
            burnRate: 0.86, moat: 300, shipRate: 0.08, foresight: 0,
            pivotSpeed: 0, leverage: -0.6, networking: 0, hallucination: 0,
            spite: 0.06, greed: 0.93, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r12 spent=360 counters=5 internalWr=58.4% vsOldMeta=52.4%
    acolyte: {
        id: "acolyte",
        attributes: {
            burnRate: 0, moat: 148.6753, shipRate: 0.7106, foresight: 0,
            pivotSpeed: 0, leverage: -0.3642, networking: 0.7106, hallucination: 0,
            spite: -0.1584, greed: 0.533, pacing: 0.0748, cunning: 0.3366,
        },
    },
    // evolved id=r13 spent=222 counters=1 internalWr=59.9% vsOldMeta=56.6%
    intern: {
        id: "intern",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.38, foresight: 0.0125,
            pivotSpeed: 0.9, leverage: -0.36, networking: 0, hallucination: 0,
            spite: -1, greed: 0.57, pacing: 0, cunning: 0,
        },
    },
    // evolved id=r14 spent=313 counters=9 internalWr=42.3% vsOldMeta=78.1%
    troll: {
        id: "troll",
        attributes: {
            burnRate: 0, moat: 168, shipRate: 0, foresight: 0,
            pivotSpeed: 0.05, leverage: -0.36, networking: 0.61, hallucination: 0,
            spite: -1, greed: 0.57, pacing: 0.66, cunning: 0.36,
        },
    },
    // evolved id=r15 spent=199 counters=5 internalWr=53.7% vsOldMeta=50.0%
    acquirer: {
        id: "acquirer",
        attributes: {
            burnRate: 0, moat: 243, shipRate: 0, foresight: 0,
            pivotSpeed: 0, leverage: -0.6, networking: 0.01, hallucination: 0,
            spite: -0.94, greed: 0.88, pacing: 0.01, cunning: 0.05,
        },
    },
};
// A few illustrative DSL-based trajectories users can copy & tweak.
export const SAMPLE_TRAJECTORIES = [
    {
        id: "ramp-aggro",
        attributes: {
            burnRate: "0.3 + 0.6 * clamp(tick / 1200, 0, 1)",
            moat: 90, shipRate: 0.9,
            pivotSpeed: "self.hp < 40 ? 0.9 : 0.2",
        },
    },
    {
        id: "oscillate-spacer",
        attributes: {
            burnRate: 0.6,
            moat: "90 + 30 * sin(tick * 0.013)",
            shipRate: 0.9, pivotSpeed: 0.6,
        },
    },
    {
        id: "panic-switcher",
        attributes: {
            burnRate: "self.hp < 30 ? 1.0 : 0.4",
            moat: "self.hp < 30 ? 0 : 100",
            shipRate: 1.0,
            hallucination: "self.hp < 20 ? 60 : 5",
        },
    },
];
