// Named strategy presets — EVOLVED roster. Generated by install-roster
// from a roster-evolve run on the bug-fixed sim. Names are preserved
// from the prior roster; attributes come from diversity-aware evolution
// against a co-evolving opponent pool. See pareto/src/roster-evolve.ts.
export const STRATEGY_NAMES = [
    "standby",
    "blitz",
    "incumbent",
    "pivot",
    "unicorn",
    "disruptor",
    "operator",
    "oracle",
    "shipper",
    "moonshot",
    "regulatory",
    "founder",
    "acolyte",
    "intern",
    "troll",
    "acquirer",
];
export const STRATEGIES = {
    // evolved id=standby spent=328 counters=0 internalWr=50.7% vsOldMeta=n/a
    standby: {
        id: "standby",
        attributes: {
            burnRate: 0.31, moat: 93, shipRate: 0.34, foresight: 0.03,
            pivotSpeed: 0, leverage: 0.5, networking: 0.49, hallucination: 0,
            spite: -0.78, greed: 0.32, pacing: 0.19, cunning: 0.34,
        },
    },
    // evolved id=blitz spent=359 counters=0 internalWr=58.3% vsOldMeta=n/a
    blitz: {
        id: "blitz",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.4, foresight: 0.15,
            pivotSpeed: 0.39, leverage: 0.48, networking: 0, hallucination: 0,
            spite: 0.66, greed: 0.47, pacing: 0.16, cunning: 0,
        },
    },
    // evolved id=incumbent spent=360 counters=0 internalWr=53.5% vsOldMeta=n/a
    incumbent: {
        id: "incumbent",
        attributes: {
            burnRate: 0, moat: 267, shipRate: 0.67, foresight: 0,
            pivotSpeed: 0.54, leverage: 0.48, networking: 0.05, hallucination: 0,
            spite: -0.28, greed: 0, pacing: 0, cunning: 0.35,
        },
    },
    // evolved id=pivot spent=359 counters=0 internalWr=52.3% vsOldMeta=n/a
    pivot: {
        id: "pivot",
        attributes: {
            burnRate: 0.22, moat: 150, shipRate: 0.58, foresight: 0.135,
            pivotSpeed: 0, leverage: 0.08, networking: 0.59, hallucination: 0,
            spite: 0.24, greed: 0, pacing: 0, cunning: 0,
        },
    },
    // evolved id=unicorn spent=336 counters=0 internalWr=55.6% vsOldMeta=n/a
    unicorn: {
        id: "unicorn",
        attributes: {
            burnRate: 0.16, moat: 15, shipRate: 1, foresight: 0.0425,
            pivotSpeed: 0, leverage: 0.5, networking: 0.87, hallucination: 0,
            spite: -0.88, greed: 0.01, pacing: 0.1, cunning: 0.19,
        },
    },
    // evolved id=disruptor spent=360 counters=0 internalWr=53.2% vsOldMeta=n/a
    disruptor: {
        id: "disruptor",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.68, foresight: 0.205,
            pivotSpeed: 0.25, leverage: 0.06, networking: 0, hallucination: 0,
            spite: 0.18, greed: 0.63, pacing: 0.1, cunning: 0,
        },
    },
    // evolved id=operator spent=306 counters=0 internalWr=47.6% vsOldMeta=n/a
    operator: {
        id: "operator",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.81, foresight: 0.1825,
            pivotSpeed: 0, leverage: 0, networking: 0, hallucination: 0,
            spite: 1, greed: 0.02, pacing: 0, cunning: 0,
        },
    },
    // evolved id=oracle spent=360 counters=0 internalWr=49.7% vsOldMeta=n/a
    oracle: {
        id: "oracle",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.56, foresight: 0.155,
            pivotSpeed: 0.44, leverage: 0, networking: 0, hallucination: 0,
            spite: -0.4, greed: 0.53, pacing: 0.45, cunning: 0.2,
        },
    },
    // evolved id=shipper spent=360 counters=0 internalWr=48.6% vsOldMeta=n/a
    shipper: {
        id: "shipper",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.56, foresight: 0.155,
            pivotSpeed: 0.44, leverage: 0, networking: 0, hallucination: 0,
            spite: -0.4, greed: 0.53, pacing: 0.65, cunning: 0,
        },
    },
    // evolved id=moonshot spent=360 counters=0 internalWr=46.5% vsOldMeta=n/a
    moonshot: {
        id: "moonshot",
        attributes: {
            burnRate: 0.2, moat: 0, shipRate: 0.56, foresight: 0.155,
            pivotSpeed: 0.24, leverage: 0, networking: 0, hallucination: 0,
            spite: -0.4, greed: 0.53, pacing: 0.45, cunning: 0.2,
        },
    },
    // evolved id=regulatory spent=360 counters=0 internalWr=46.8% vsOldMeta=n/a
    regulatory: {
        id: "regulatory",
        attributes: {
            burnRate: 0, moat: 162, shipRate: 0.67, foresight: 0,
            pivotSpeed: 0.89, leverage: 0.48, networking: 0, hallucination: 0,
            spite: -0.18, greed: 0, pacing: 0, cunning: 0.35,
        },
    },
    // evolved id=founder spent=359 counters=0 internalWr=45.9% vsOldMeta=n/a
    founder: {
        id: "founder",
        attributes: {
            burnRate: 0.49, moat: 150, shipRate: 0.55, foresight: 0.135,
            pivotSpeed: 0, leverage: 0.08, networking: 0.05, hallucination: 0,
            spite: 0.14, greed: 0, pacing: 0.25, cunning: 0.1,
        },
    },
    // evolved id=acolyte spent=321 counters=0 internalWr=48.2% vsOldMeta=n/a
    acolyte: {
        id: "acolyte",
        attributes: {
            burnRate: 0.05, moat: 0, shipRate: 0.49, foresight: 0.0075,
            pivotSpeed: 0.01, leverage: 0.26, networking: 0, hallucination: 0,
            spite: 0.18, greed: 0.63, pacing: 0, cunning: 0.78,
        },
    },
    // evolved id=intern spent=336 counters=0 internalWr=54.2% vsOldMeta=n/a
    intern: {
        id: "intern",
        attributes: {
            burnRate: 0.35, moat: 15, shipRate: 1, foresight: 0.0425,
            pivotSpeed: 0, leverage: 0.5, networking: 0.87, hallucination: 0,
            spite: -0.88, greed: 0.01, pacing: 0.1, cunning: 0,
        },
    },
    // evolved id=troll spent=360 counters=0 internalWr=46.2% vsOldMeta=n/a
    troll: {
        id: "troll",
        attributes: {
            burnRate: 0, moat: 0, shipRate: 0.68, foresight: 0.205,
            pivotSpeed: 0.35, leverage: 0.06, networking: 0, hallucination: 0,
            spite: 0.38, greed: 0.53, pacing: 0, cunning: 0,
        },
    },
    // evolved id=acquirer spent=359 counters=0 internalWr=46.2% vsOldMeta=n/a
    acquirer: {
        id: "acquirer",
        attributes: {
            burnRate: 0.65, moat: 21, shipRate: 0.58, foresight: 0.13,
            pivotSpeed: 0, leverage: -0.76, networking: 0, hallucination: 0,
            spite: 0.36, greed: 0, pacing: 0.61, cunning: 0.36,
        },
    },
};
// A few illustrative DSL-based trajectories users can copy & tweak.
export const SAMPLE_TRAJECTORIES = [
    {
        id: "ramp-aggro",
        attributes: {
            burnRate: "0.3 + 0.6 * clamp(tick / 1200, 0, 1)",
            moat: 90, shipRate: 0.9,
            pivotSpeed: "self.hp < 40 ? 0.9 : 0.2",
        },
    },
    {
        id: "oscillate-spacer",
        attributes: {
            burnRate: 0.6,
            moat: "90 + 30 * sin(tick * 0.013)",
            shipRate: 0.9, pivotSpeed: 0.6,
        },
    },
    {
        id: "panic-switcher",
        attributes: {
            burnRate: "self.hp < 30 ? 1.0 : 0.4",
            moat: "self.hp < 30 ? 0 : 100",
            shipRate: 1.0,
            hallucination: "self.hp < 20 ? 60 : 5",
        },
    },
];
