// Named strategy presets — EVOLVED roster. Generated by install-roster
// from a roster-evolve run on the bug-fixed sim. Names are preserved
// from the prior roster; attributes come from diversity-aware evolution
// against a co-evolving opponent pool. See pareto/src/roster-evolve.ts.
export const STRATEGY_NAMES = [
    "standby",
    "blitz",
    "incumbent",
    "pivot",
    "unicorn",
    "disruptor",
    "operator",
    "oracle",
    "shipper",
    "moonshot",
    "regulatory",
    "founder",
    "acolyte",
    "intern",
    "troll",
    "acquirer",
];
export const STRATEGIES = {
    // evolved id=standby spent=360 counters=6 internalWr=55.1% vsOldMeta=56.3%
    standby: {
        id: "standby",
        attributes: {
            burnRate: 0.16, moat: 42, shipRate: 0.37, foresight: 0.045,
            pivotSpeed: 0.46, leverage: 0.14, networking: 0.46, hallucination: 0,
            spite: -0.6, greed: 0.15, pacing: 0.56, cunning: 0.35,
        },
    },
    // evolved id=blitz spent=360 counters=7 internalWr=46.9% vsOldMeta=54.9%
    blitz: {
        id: "blitz",
        attributes: {
            burnRate: 0.6457, moat: 0, shipRate: 0.313, foresight: 0.1395,
            pivotSpeed: 0.2675, leverage: -0.1201, networking: 0.6153, hallucination: 0,
            spite: 0.2461, greed: 0, pacing: 0.0746, cunning: 0.0631,
        },
    },
    // evolved id=incumbent spent=360 counters=2 internalWr=56.9% vsOldMeta=49.3%
    incumbent: {
        id: "incumbent",
        attributes: {
            burnRate: 0, moat: 175.298, shipRate: 0.4371, foresight: 0.2105,
            pivotSpeed: 0.3612, leverage: -0.3654, networking: 0.7107, hallucination: 0,
            spite: -0.6951, greed: 0.1855, pacing: 0.0092, cunning: 0,
        },
    },
    // evolved id=pivot spent=332 counters=8 internalWr=41.6% vsOldMeta=58.7%
    pivot: {
        id: "pivot",
        attributes: {
            burnRate: 0.0521, moat: 0, shipRate: 0.4401, foresight: 0.1214,
            pivotSpeed: 0.9304, leverage: -0.204, networking: 0, hallucination: 0,
            spite: 0.1774, greed: 0, pacing: 0.3185, cunning: 0.1024,
        },
    },
    // evolved id=unicorn spent=360 counters=0 internalWr=75.4% vsOldMeta=72.9%
    unicorn: {
        id: "unicorn",
        attributes: {
            burnRate: 0.2567, moat: 164.3863, shipRate: 0.4126, foresight: 0.2236,
            pivotSpeed: 0.2154, leverage: -0.119, networking: 0.022, hallucination: 0,
            spite: -0.6672, greed: 0.4993, pacing: 0, cunning: 0.1449,
        },
    },
    // evolved id=disruptor spent=314 counters=1 internalWr=68.7% vsOldMeta=83.7%
    disruptor: {
        id: "disruptor",
        attributes: {
            burnRate: 0.0673, moat: 13.9832, shipRate: 0.4265, foresight: 0.1961,
            pivotSpeed: 0.4184, leverage: -0.1391, networking: 0.1858, hallucination: 0,
            spite: 0.2876, greed: 0, pacing: 0.0983, cunning: 0.0354,
        },
    },
    // evolved id=operator spent=358 counters=4 internalWr=57.4% vsOldMeta=63.9%
    operator: {
        id: "operator",
        attributes: {
            burnRate: 0.5069, moat: 13.9832, shipRate: 0.3873, foresight: 0.1636,
            pivotSpeed: 0.3181, leverage: 0.059, networking: 0.0872, hallucination: 0,
            spite: 0.0804, greed: 0, pacing: 0.2559, cunning: 0.2513,
        },
    },
    // evolved id=oracle spent=348 counters=9 internalWr=39.7% vsOldMeta=60.8%
    oracle: {
        id: "oracle",
        attributes: {
            burnRate: 0.0219, moat: 148.4368, shipRate: 0.4973, foresight: 0.2284,
            pivotSpeed: 0.5451, leverage: -0.8293, networking: 0, hallucination: 0,
            spite: 0.6266, greed: 0.0127, pacing: 0, cunning: 0.0966,
        },
    },
    // evolved id=shipper spent=353 counters=8 internalWr=43.7% vsOldMeta=60.4%
    shipper: {
        id: "shipper",
        attributes: {
            burnRate: 0.0873, moat: 13.9832, shipRate: 0.786, foresight: 0.104,
            pivotSpeed: 0.1181, leverage: -0.204, networking: 0.4014, hallucination: 0,
            spite: 0.5334, greed: 0, pacing: 0.4548, cunning: 0.059,
        },
    },
    // evolved id=moonshot spent=320 counters=8 internalWr=38.7% vsOldMeta=69.1%
    moonshot: {
        id: "moonshot",
        attributes: {
            burnRate: 0, moat: 135.0544, shipRate: 0.3354, foresight: 0.1355,
            pivotSpeed: 0.5669, leverage: 0.6445, networking: 0.0183, hallucination: 0,
            spite: -0.0721, greed: 0, pacing: 0.0039, cunning: 0,
        },
    },
    // evolved id=regulatory spent=356 counters=6 internalWr=45.1% vsOldMeta=56.3%
    regulatory: {
        id: "regulatory",
        attributes: {
            burnRate: 0, moat: 54.8109, shipRate: 0.3725, foresight: 0.1831,
            pivotSpeed: 0.296, leverage: -0.3204, networking: 0, hallucination: 0,
            spite: 0.0125, greed: 0.4617, pacing: 0.2723, cunning: 0.3935,
        },
    },
    // evolved id=founder spent=340 counters=14 internalWr=23.3% vsOldMeta=62.5%
    founder: {
        id: "founder",
        attributes: {
            burnRate: 0.14, moat: 117, shipRate: 0.4031, foresight: 0.025,
            pivotSpeed: 0.1868, leverage: -0.7444, networking: 0.4425, hallucination: 0,
            spite: -0.36, greed: 0.6434, pacing: 0.38, cunning: 0.2655,
        },
    },
    // evolved id=acolyte spent=352 counters=7 internalWr=44.8% vsOldMeta=54.9%
    acolyte: {
        id: "acolyte",
        attributes: {
            burnRate: 0.645, moat: 0, shipRate: 0.3935, foresight: 0.1957,
            pivotSpeed: 0.7834, leverage: -0.878, networking: 0, hallucination: 0,
            spite: 0.2379, greed: 0.0448, pacing: 0.0945, cunning: 0.0988,
        },
    },
    // evolved id=intern spent=360 counters=5 internalWr=48.6% vsOldMeta=64.9%
    intern: {
        id: "intern",
        attributes: {
            burnRate: 0.31, moat: 0, shipRate: 0.3153, foresight: 0.1217,
            pivotSpeed: 0.1682, leverage: -0.2067, networking: 0.2974, hallucination: 0,
            spite: 0.1853, greed: 0.7741, pacing: 0, cunning: 0.2591,
        },
    },
    // evolved id=troll spent=360 counters=6 internalWr=52.8% vsOldMeta=75.3%
    troll: {
        id: "troll",
        attributes: {
            burnRate: 0.366, moat: 33.1564, shipRate: 0.4071, foresight: 0.0499,
            pivotSpeed: 0.1928, leverage: -0.0037, networking: 0.1197, hallucination: 0,
            spite: 0.2067, greed: 0.2118, pacing: 0.458, cunning: 0.4329,
        },
    },
    // evolved id=acquirer spent=360 counters=2 internalWr=61.4% vsOldMeta=53.5%
    acquirer: {
        id: "acquirer",
        attributes: {
            burnRate: 0, moat: 9.5885, shipRate: 0.4408, foresight: 0.1521,
            pivotSpeed: 0.4446, leverage: -0.0433, networking: 0.816, hallucination: 0,
            spite: 0.1558, greed: 0.1236, pacing: 0.043, cunning: 0.0353,
        },
    },
};
// A few illustrative DSL-based trajectories users can copy & tweak.
export const SAMPLE_TRAJECTORIES = [
    {
        id: "ramp-aggro",
        attributes: {
            burnRate: "0.3 + 0.6 * clamp(tick / 1200, 0, 1)",
            moat: 90, shipRate: 0.9,
            pivotSpeed: "self.hp < 40 ? 0.9 : 0.2",
        },
    },
    {
        id: "oscillate-spacer",
        attributes: {
            burnRate: 0.6,
            moat: "90 + 30 * sin(tick * 0.013)",
            shipRate: 0.9, pivotSpeed: 0.6,
        },
    },
    {
        id: "panic-switcher",
        attributes: {
            burnRate: "self.hp < 30 ? 1.0 : 0.4",
            moat: "self.hp < 30 ? 0 : 100",
            shipRate: 1.0,
            hallucination: "self.hp < 20 ? 60 : 5",
        },
    },
];
