// Installs a roster JSON (from roster-evolve) as the canonical STRATEGIES.
// Preserves the 16 STRATEGY_NAMES; replaces attributes with the evolved
// configs in roster order (roster[i] → STRATEGY_NAMES[i]).
//
// Writes sim/src/strategies.ts. Caller must rebuild + sync client/sim/.

import fs from "node:fs";
import path from "node:path";

const ROSTER_PATH = process.argv[2] ?? "/tmp/new-roster-fixed.json";
const STRATEGIES_PATH = path.resolve(process.cwd(), "sim/src/strategies.ts");

const NAMES = [
  "standby", "blitz", "incumbent", "pivot",
  "thesis", "disruptor", "operator", "oracle",
  "shipper", "moonshot", "regulatory", "founder",
  "acolyte", "cassandra", "troll", "acquirer",
];

interface RosterJSON {
  roster: Array<{
    id: string;
    attributes: Record<string, number>;
    spent: number;
    internalWr: number;
    counters: number;
    vsOldMeta: number;
  }>;
}

const data: RosterJSON = JSON.parse(fs.readFileSync(ROSTER_PATH, "utf8"));
if (data.roster.length < NAMES.length) {
  console.error(`Roster has ${data.roster.length} configs, need ${NAMES.length}`);
  process.exit(1);
}

function fmtNum(n: number): string {
  if (Number.isInteger(n)) return n.toString();
  return n.toFixed(4).replace(/0+$/, "").replace(/\.$/, "");
}

function attrLine(attrs: Record<string, number>): string {
  const keys = [
    "burnRate", "moat", "shipRate", "foresight",
    "pivotSpeed", "leverage", "networking", "hallucination",
    "spite", "greed", "pacing", "cunning",
  ];
  const parts = keys.map((k) => `${k}: ${fmtNum(attrs[k] ?? 0)}`);
  return `      ${parts.slice(0, 4).join(", ")},\n      ${parts.slice(4, 8).join(", ")},\n      ${parts.slice(8).join(", ")},`;
}

let body = `// Named strategy presets — EVOLVED roster. Generated by install-roster
// from a roster-evolve run on the bug-fixed sim. Names are preserved
// from the prior roster; attributes come from diversity-aware evolution
// against a co-evolving opponent pool. See pareto/src/roster-evolve.ts.

import type { BrainConfig } from "./types.js";

export const STRATEGY_NAMES = [
${NAMES.map((n) => `  "${n}",`).join("\n")}
] as const;
export type StrategyName = (typeof STRATEGY_NAMES)[number];

export const STRATEGIES: Record<StrategyName, BrainConfig> = {
`;

for (let i = 0; i < NAMES.length; i++) {
  const name = NAMES[i];
  const r = data.roster[i];
  const comment = `  // evolved id=${r.id} spent=${r.spent} counters=${r.counters} internalWr=${(r.internalWr * 100).toFixed(1)}% vsOldMeta=${(r.vsOldMeta * 100).toFixed(1)}%`;
  body += `${comment}\n`;
  body += `  ${name}: {\n    id: "${name}",\n    attributes: {\n${attrLine(r.attributes)}\n    },\n  },\n`;
}

body += `};\n\n`;
body += `// A few illustrative DSL-based trajectories users can copy & tweak.\n`;
body += `export const SAMPLE_TRAJECTORIES: BrainConfig[] = [\n`;
body += `  {\n    id: "ramp-aggro",\n    attributes: {\n      burnRate: "0.3 + 0.6 * clamp(tick / 1200, 0, 1)",\n      moat: 90, shipRate: 0.9,\n      pivotSpeed: "self.hp < 40 ? 0.9 : 0.2",\n    },\n  },\n`;
body += `  {\n    id: "oscillate-spacer",\n    attributes: {\n      burnRate: 0.6,\n      moat: "90 + 30 * sin(tick * 0.013)",\n      shipRate: 0.9, pivotSpeed: 0.6,\n    },\n  },\n`;
body += `  {\n    id: "panic-switcher",\n    attributes: {\n      burnRate: "self.hp < 30 ? 1.0 : 0.4",\n      moat: "self.hp < 30 ? 0 : 100",\n      shipRate: 1.0,\n      hallucination: "self.hp < 20 ? 60 : 5",\n    },\n  },\n`;
body += `];\n`;

fs.writeFileSync(STRATEGIES_PATH, body);
console.log(`Wrote ${STRATEGIES_PATH} (${NAMES.length} presets)`);
console.log(`\nRoster summary:`);
for (let i = 0; i < NAMES.length; i++) {
  const r = data.roster[i];
  console.log(`  ${NAMES[i].padEnd(12)}  spent=${String(r.spent).padStart(3)}  counters=${String(r.counters).padStart(2)}  internal=${(r.internalWr*100).toFixed(1).padStart(5)}%  vsOld=${(r.vsOldMeta*100).toFixed(1).padStart(5)}%`);
}
