export interface ComputeUseCase {
  id: string;
  title: string;
  status: "implemented" | "experimental" | "planned";
  workload?: string;
  authority: "advisory";
  inputBoundary: string;
  validation: string;
  notes: string;
  publicEndpoint?: string;
}

export const COMPUTE_USE_CASES: ComputeUseCase[] = [
  {
    id: "replay-verification",
    title: "Replay artifact verification",
    status: "implemented",
    workload: "m3t4.replay_verify.v1",
    authority: "advisory",
    inputBoundary: "public replay artifact with action bytes; private player configs rejected",
    validation: "2-of-2 assignment-bound receipts against server-held expected hashes",
    notes: "First useful workload from the plan. Re-simulates public replay action logs, does not receive expected outputs in assignment payloads, and never receives ranked authority.",
  },
  {
    id: "public-artifact-verification",
    title: "Public artifact hash verification",
    status: "implemented",
    workload: "m3t4.public_artifact_verify.v0",
    authority: "advisory",
    inputBoundary: "public replay artifact payload only",
    validation: "2-of-2 assignment-bound receipts against server-held expected hashes",
    notes: "Integrity scaffold for exported public artifacts and WebRTC data-plane transport tests. Assignment payloads do not expose expected outputs or the server-held artifact hash; strict WebRTC proof tasks require server-issued peer subassignments and peer-signed subreceipts.",
  },
  {
    id: "seed-sweeps",
    title: "Public preset seed sweeps",
    status: "implemented",
    workload: "m3t4.seed_sweep.v0",
    authority: "advisory",
    inputBoundary: "public stage ids and public preset names only",
    validation: "assignment-bound receipts against server-held deterministic reference output",
    notes: "Useful for meta-health and balance diagnostics. Opted-in browsers advertise this as a CPU browser-JS workload bound to sim constants and behavior version.",
  },
  {
    id: "device-witness-webgpu",
    title: "Device Witness: WebGPU conformance",
    status: "implemented",
    workload: "device_witness.webgpu.v0",
    authority: "advisory",
    inputBoundary: "bucketed opt-in browser capability plus assignment-bound tiny WebGPU challenge",
    validation: "expected-hash receipt for deterministic u32 buffer transform",
    notes: "Reports coarse WebGPU availability, correctness, and runtime buckets after opt-in; no raw adapter strings.",
  },
  {
    id: "tensor-tiles",
    title: "WebGPU tensor tiles",
    status: "implemented",
    workload: "plasma.tensor_tile.v0",
    authority: "advisory",
    inputBoundary: "public deterministic u32 tensor tile params only",
    validation: "assignment-bound expected-hash receipts against a server-held CPU reference output",
    notes: "First real WebGPU useful-work fixture beyond Device Witness. It runs a bounded integer matrix/tensor tile in browser WebGPU and only schedules to workers promoted to webgpu-light.",
  },
  {
    id: "device-witness-webrtc",
    title: "Device Witness: WebRTC connectivity",
    status: "implemented",
    workload: "device_witness.webrtc.v0",
    authority: "advisory",
    inputBoundary: "bucketed opt-in HTTP/WebRTC observations plus assignment-bound local transcript receipts",
    validation: "measurement receipt hash over issued challenge params and whitelisted transcript buckets",
    notes: "Measures HTTP RTT, local and signaled two-browser datachannel open, ICE candidate type buckets, and optional STUN/TURN outcomes. Raw network details stay admin-only.",
  },
  {
    id: "device-witness-render-fixtures",
    title: "Device Witness: rendering fixtures",
    status: "implemented",
    workload: "device_witness.render_fixture.v0",
    authority: "advisory",
    inputBoundary: "tiny worker-side OffscreenCanvas fixture samples",
    validation: "expected-hash receipt for pixel sample bytes plus observation buckets",
    notes: "Catches alpha/compositing/rendering drift without collecting full images or exact device identifiers.",
  },
  {
    id: "device-witness-derived-buffer",
    title: "Device Witness: derived buffer fixture",
    status: "implemented",
    workload: "device_witness.derived_buffer.v0",
    authority: "advisory",
    inputBoundary: "synthetic public byte buffer only; no game frame, private config, or render resource",
    validation: "expected-hash receipt plus derived source/region/kernel/output evidence",
    notes: "Exercises the Plasma derived-compute receipt shape before any real shared renderer buffer exists.",
  },
  {
    id: "webrtc-data-plane",
    title: "Plasma WebRTC data plane",
    status: "experimental",
    authority: "advisory",
    inputBoundary: "short-lived opaque signaling payloads and bucketed connectivity receipts",
    validation: "same assignment and receipt contract as HTTP plus task-required WebRTC transport, server-issued peer subassignments, and peer-signed data-channel subreceipts",
    notes: "Pairing/signaling and data-channel witness execution are separately flagged; public assignment intake remains independently gated.",
  },
  {
    id: "device-witness-profiles",
    title: "Device Witness profiles",
    status: "implemented",
    authority: "advisory",
    inputBoundary: "derived from admin-only receipts and bucketed observations",
    validation: "profile scores are summaries, not task truth",
    notes: "Feeds scheduler intelligence: allowed workload tier comes from accepted witness receipts; self-reported buckets remain scoring and dashboard hints.",
  },
  {
    id: "exploit-search",
    title: "Exploit search",
    status: "implemented",
    workload: "m3t4.exploit_search.v0",
    authority: "advisory",
    inputBoundary: "public/system opponents or explicitly published configs",
    validation: "assignment-bound expected-hash receipts over deterministic telemetry summaries and flagged seed findings",
    notes: "Scans bounded public preset seed windows for timeout draws, clash loops, escape spirals, objective thrash, and side-bias evidence. It stays strictly off ranked/private brains.",
  },
  {
    id: "asset-processing",
    title: "Asset processing",
    status: "implemented",
    workload: "asset.tile_audit.v0",
    authority: "advisory",
    inputBoundary: "public image tiles or generated assets",
    validation: "assignment-bound expected-hash receipts over deterministic trim, palette, edge-bleed, and alpha audit summaries",
    notes: "First asset lane is an audit, not an opaque transform job. It measures trim rects, dominant colors, fringe alpha, and bleed risk for sprite/tileset cleanup.",
  },
  {
    id: "embedding-batches",
    title: "Embedding and rerank batches",
    status: "experimental",
    workload: "ml.embedding_tile.v0",
    authority: "advisory",
    inputBoundary: "public text, image, or published corpus shards only",
    validation: "replicated quorum on quantized top-k hashes for public retrieval tiles; later add tolerance-bounded vector checks",
    notes: "First Doppler-backed ML workload. Browser WebGPU workers run EmbeddingGemma retrieval tiles and agree on quantized rerank outputs without giving ranked authority to the sidecar.",
  },
  {
    id: "prefill-topk-probes",
    title: "Prompt prefill top-k probes",
    status: "experimental",
    workload: "ml.prefill_topk_probe.v0",
    authority: "advisory",
    inputBoundary: "public prompt text only, capped to a bounded short prompt length",
    validation: "replicated quorum on canonical top-k token-id receipts from a fixed browser model",
    notes: "First Doppler-backed text-generation probe. Browser WebGPU workers run a bounded prefill on a small fixed model and return only the next-token top-k IDs, which is small enough to receipt cleanly before attempting branch decode or KV transport.",
  },
  {
    id: "logit-divergence",
    title: "Cross-hardware logit divergence measurement",
    status: "experimental",
    workload: "ml.logit_divergence.v0",
    authority: "advisory",
    inputBoundary: "public prompt text only, capped to a bounded short prompt length",
    validation: "tolerance-bounded measurement receipts carrying quantized top-k logit buckets plus delta-from-top; receipts are signed and persisted regardless of inter-hardware agreement",
    notes: "Extension of ml.prefill_topk_probe.v0 intended as a cross-vendor WebGPU measurement instrument. Each receipt captures a quantized logit fingerprint for one (prompt, hardware) pair; outliers are kept rather than rejected because the divergence across vendors is the artifact.",
  },
  {
    id: "image-tile-inference",
    title: "Image tile inference",
    status: "implemented",
    workload: "ml.image_tile_infer.v0",
    authority: "advisory",
    inputBoundary: "public image tiles only; no private uploads in the first phase",
    validation: "assignment-bound expected-hash receipts over a fixed low-bandwidth tile classifier",
    notes: "First phase is a deterministic fixed classifier over bounded RGBA tiles, returning top-k labels and feature scores without a heavyweight model download. It is the low-bandwidth bridge into richer image lanes later.",
  },
  {
    id: "microscopy-tiles",
    title: "Microscopy tile scoring",
    status: "implemented",
    workload: "science.microscopy_tile_score.v0",
    authority: "advisory",
    inputBoundary: "public microscopy or pathology tiles with published labels or controls",
    validation: "assignment-bound expected-hash receipts over deterministic microscopy scorecards",
    notes: "Science-shaped without overclaiming. It scores focus, stain balance, cellularity, artifact risk, and anomaly heuristics on bounded public tiles without claiming diagnosis or hidden truth.",
  },
  {
    id: "contact-map-tiles",
    title: "Protein contact-map tiles",
    status: "experimental",
    workload: "science.contact_map_tile.v0",
    authority: "advisory",
    inputBoundary: "public residue windows from published proteins only; no private sequences or hidden labels",
    validation: "assignment-bound expected-hash receipts against a server-held integer contact-score tile reference",
    notes: "Low-bandwidth protein-shaped workload. Browser WebGPU workers score bounded residue-window tiles with a deterministic heuristic contact function, which is honest enough to ship now without claiming learned folding or hidden science truth. A public aggregate of accepted receipts is served at /compute/public/contact-map/aggregate.",
    publicEndpoint: "/compute/public/contact-map/aggregate",
  },
  {
    id: "genome-kmer",
    title: "Reference genome k-mer histograms",
    status: "implemented",
    workload: "science.genome_kmer.v0",
    authority: "advisory",
    inputBoundary: "public ACGT-only reference-genome windows up to 256 bases; no private or unpublished sequences",
    validation: "assignment-bound expected-hash receipts against a server-held CPU reference k-mer histogram",
    notes: "Low-bandwidth bioinformatics lane. Deterministic CPU kernel producing a u32 k-mer count histogram for k in 2..6 over a bounded DNA window. Useful as a receipt-backed reproducibility primitive for taxonomy, contamination, and composition-based public-genome studies.",
  },
];
